### ISSUE TITLE
Add about page

### ISSUE THREAD

**Issue by RaedsLab** [RaedsLab/showcase-react#3]
**Is your feature request related to a problem? Please describe.**
Add a page that describes the tech and goals of this project.

**Describe the solution you'd like**
We need react-router and a way to navigate pages ideally with suspense and pre-fetch.

**Describe alternatives you've considered**
In-house router

**Additional context**
None.

**Comment by SHITianhao** [comment]
Maybe you can have a live demo ;) I'm just lazy to download it

**Comment by RaedsLab** [comment]
@SHITianhao actually in the project page there is a demo link: https://showcase.raed.it/  ;)

**Comment by SHITianhao** [comment]
oooops:
![image](https://user-images.githubusercontent.com/7813681/50028932-16626000-ffa6-11e8-9e17-e42aef17542c.png)

Console error
```json
{
"error":
  {
      "*": "See https://en.wikipedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.",
     "code": "nosearch",
     "info": "The 'search' parameter must be set.",
     "servedby": "mw1281"
  }
}
```

**Comment by SHITianhao** [comment]
BTW, any plan to try React Hooks? You might not need Redux lol

**Comment by RaedsLab** [comment]
Thanks for the error report! what did you do to trigger the error I changed values on the left menu and can't seem to reproduce!

**Comment by RaedsLab** [comment]
for react hooks i added #4 beyond hello world i haven't had the time to try them yet

**Comment by RaedsLab** [comment]
@SHITianhao tested react hooks check [codesandbox](https://codesandbox.io/s/yq6lvqxo6x) but enzyme does not support hooks yet, so it breaks tests.
